/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caixaeletronico;

import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class InterfaceCaixaEletronico extends javax.swing.JFrame {

    Conta objConta = null;
    ContaEspecial objContaEspecial = null;

    /**
     * Creates new form InterfaceCaixaEletronico
     */
    public InterfaceCaixaEletronico(Conta objConta) {
        initComponents();
        this.objConta = objConta;
        this.setLocationRelativeTo(null);

    }

    public InterfaceCaixaEletronico(ContaEspecial objEspecial) {
        initComponents();
        this.objContaEspecial = objEspecial;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_saida = new javax.swing.JTextArea();
        btn_saldo = new javax.swing.JButton();
        btn_saque = new javax.swing.JButton();
        btn_deposito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_saida.setColumns(20);
        txt_saida.setRows(5);
        jScrollPane1.setViewportView(txt_saida);

        btn_saldo.setText("SALDO");
        btn_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saldoActionPerformed(evt);
            }
        });

        btn_saque.setText("SAQUE");
        btn_saque.setToolTipText("");
        btn_saque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saqueActionPerformed(evt);
            }
        });

        btn_deposito.setText("DEPÓSITO");
        btn_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depositoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_deposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_saque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btn_saldo)
                .addGap(18, 18, 18)
                .addComponent(btn_saque)
                .addGap(18, 18, 18)
                .addComponent(btn_deposito)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saldoActionPerformed

        //txt_saida.setText(String.valueOf(objConta.verificarSaldo()));
        txt_saida.setText(objContaEspecial.verificarSaldoEspecial());

    }//GEN-LAST:event_btn_saldoActionPerformed

    private void btn_saqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saqueActionPerformed

        /*double valor = Double.parseDouble(JOptionPane.showInputDialog("DIGITE UM VALOR DE SAQUE:"));
        txt_saida.setText(String.valueOf("SALDO ATUAL: " + objConta.verificarSaldo()));
        objConta.realizarSaque(valor);
        txt_saida.setText(String.valueOf("VALOR SACADO: " + valor));
        txt_saida.setText(String.valueOf("SALDO ATUAL: " + objConta.verificarSaldo()));
         */
    }//GEN-LAST:event_btn_saqueActionPerformed

    private void btn_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depositoActionPerformed
        /*double valor = Double.parseDouble(JOptionPane.showInputDialog("DIGITE UM VALOR DE DEPOSITO:"));
        txt_saida.setText(String.valueOf("SALDO ATUAL: " + objConta.verificarSaldo()));
        objConta.realizarDeposito(valor);
        txt_saida.setText(String.valueOf("SALDO ATUAL: " + objConta.verificarSaldo()));
         */
    }//GEN-LAST:event_btn_depositoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaixaEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaixaEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaixaEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaixaEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCaixaEletronico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deposito;
    private javax.swing.JButton btn_saldo;
    private javax.swing.JButton btn_saque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_saida;
    // End of variables declaration//GEN-END:variables
}
